push_images:
  strategy:
    matrix:
      service: ${{ env.SERVICE_MATRIX }}
  runs-on: ubuntu-latest
  needs: build_jars
  steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
    - name: Create buildx builder
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Prepare location environments
      run: echo "LOCATION=`pwd`/${{ matrix.service }}" >> $GITHUB_ENV
    - name: Download app JAR artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ matrix.service }}_jar
        path: ${{ env.LOCATION }}
    - name: Download TAGs artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ matrix.service }}_tags_file
        path: ${{ env.LOCATION }}

    - name: Create image
      uses: docker/build-push-action@v4.0.0
      with:
        context: ${{ matrix.service }}
        file: ./config/dockerfiles/Dockerfile-${{ matrix.service }}
        push: true
        builder: mybuilder
        platforms: linux/amd64, linux/arm64, linux/386, linux/arm/v7, linux/arm/v6
        tags: $(cat ${{ matrix.service }}_tags.tmp | tr '\n' ',')