version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    container_name: "rabbit"
    pull_policy: always
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pswrd
    network_mode: host