version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_IP: 192.168.50.132
  TORRENT_IP: 192.168.50.132

  BOT_TOKEN: 6103416881:AAFSQ_hGImrAI05FaAGnx4Yez2eZM9M5uJc
  BOT_NAME: halushko_video_bot
  BOT_TRUSTED_USERS: 43504868

  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500

  PING: /ping
  PONG: pong

  LOGS_LEVEL: info
services:
  torrent:
    image: halushko/cinema-torrent:alpha
    environment: *common-variables
    restart: always
    container_name: "torrent"
    volumes:
      - ./workdir/config/transmission:/home/app/transmission_config
      - ./workdir/config/transmission_hdd:/home/app/transmission_config_hdd
      - ./workdir/config/logs:/home/app/logs
    network_mode: host
  bot:
    image: halushko/cinema-bot:alpha
    environment: *common-variables
    restart: always
    container_name: "bot"
    volumes:
      - ./workdir/config/logs:/home/app/logs
    networks:
      bot_network_local:
  text:
    image: halushko/cinema-text:alpha
    environment: *common-variables
    restart: always
    container_name: "text"
    volumes:
      - ./workdir/config/logs:/home/app/logs
    networks:
      bot_network_local:
  file:
    image: halushko/cinema-file:alpha
    environment: *common-variables
    restart: always
    container_name: "file"
    volumes:
      - ./workdir/config/files_from_telegram:/home/torrent_files/
      - ./workdir/config/files_from_telegram_hdd:/home/torrent_files_hdd/
      - ./workdir/config/logs:/home/app/logs
    networks:
      bot_network_local:
networks:
  bot_network_local:
    driver: bridge