version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_IP: 192.168.50.132
  TORRENT_IP: 192.168.50.132

  BOT_TOKEN: 6103416881:AAFSQ_hGImrAI05FaAGnx4Yez2eZM9M5uJc
  BOT_NAME: halushko_video_bot
  BOT_TRUSTED_USERS: 43504868

  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500

  PING: /ping
  PONG: pong

  LOGS_LEVEL: debug
services:
  torrent_debug:
    image: halushko/cinema-torrent:beta
    environment: *common-variables
    restart: always
    container_name: "torrent_debug"
    volumes:
      - ./workdir/config/transmission:/home/app/transmission_config
      - ./workdir/config/logs:/home/app/logs
    network_mode: host
  bot_debug:
    image: halushko/cinema-bot:beta
    environment: *common-variables
    restart: always
    container_name: "bot_debug"
    volumes:
      - ./workdir/config/logs:/home/app/logs
    networks:
      at_private_network_debug:
  text_debug:
    image: halushko/cinema-text:beta
    environment: *common-variables
    restart: always
    container_name: "text_debug"
    volumes:
      - ./workdir/config/logs:/home/app/logs
    networks:
      at_private_network_debug:
  file_debug:
    image: halushko/cinema-file:beta
    environment: *common-variables
    restart: always
    container_name: "file_debug"
    volumes:
      - ./workdir/config/files_from_telegram:/home/torrent_files/
      - ./workdir/config/logs:/home/app/logs
    networks:
      at_private_network_debug:
networks:
  bot_network_debug:
    driver: bridge