version: '3.7'

services:
  media:
    image: lscr.io/linuxserver/plex:latest
    container_name: "media"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./workdir/config/plex/config:/config
      - ./workdir/mediadata:/movies/1
      - ./workdir/mediadata_hdd/mediadata:/movies/2
      - ./workdir/mediadata_morhun:/movies/3
      - ./workdir/mediadata_hdd/low_quality:/movies/4
    restart: always
    network_mode: host