version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_HOST_IP: 10.10.255.254

  BOT_TOKEN: <input bot token here>
  BOT_NAME: <input name of torrent here>

  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500

  DIR_TORRENT_COMPLETE: /home/media/torrent/complete/
  DIR_TORRENT_INCOMPLETE: /home/media/torrent/downloads/
  DIR_TORRENT_WATCH: /home/media/torrent/torrent_files/
  DIR_MEDIA_SHOW: /home/media/

  PING: /ping
  PONG: pong
services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment: *common-variables
    networks:
      cat_private_network:
        ipv4_address: 10.10.255.254
    ports:
      - 5672:5672
      - 15672:15672
  bot:
    image: halushko/cinema-bot:0.4-pi
    environment: *common-variables
    restart: always
    container_name: "bot"
    depends_on:
      - rabbitmq
    networks:
      cat_private_network:
        ipv4_address: 10.10.0.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256Mb
  text_handler:
    image: halushko/cinema-text:0.4-pi
    environment: *common-variables
    restart: always
    container_name: "text_handler"
    networks:
      cat_private_network:
        ipv4_address: 10.10.0.3
    depends_on:
      - rabbitmq
  file_handler:
    image: halushko/cinema-file:0.4-pi
    environment: *common-variables
    restart: always
    container_name: "file_handler"
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/torrent/torrent_files:/home/torrent_files/
    networks:
      cat_private_network:
        ipv4_address: 10.10.0.4
  torrent:
    image: halushko/cinema-torrent:0.4-pi
    environment: *common-variables
    restart: always
    container_name: "torrent"
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/:/home/media/
      - ./workdir/torrentdata/torrents:/var/lib/transmission/config/torrents
      - ./workdir/torrentdata/resume:/var/lib/transmission/config/resume
    networks:
      cat_private_network:
        ipv4_address: 10.10.0.5
    ports:
      - 9091:9091
      - 51413:51413
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  minidlna:
    container_name: "minidlna"
    image: halushko/cinema-media:0.4-pi
    restart: always
    environment:  *common-variables
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/torrent/complete:/home/media/
    network_mode: host
    ports:
      - 8200:8200
      - 1900:1900/udp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  cat_private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
