version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_HOST_IP: 172.17.0.1

  BOT_TOKEN: 1859184957:AAFE9UVpkzXE5Hh72IKj9zOfH2VsxP0Rkn8
  BOT_NAME: koTorrentBot

  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500

  DIR_TORRENT_COMPLETE: /home/media/torrent/complete/
  DIR_TORRENT_INCOMPLETE: /home/media/torrent/downloads/
  DIR_TORRENT_WATCH: /home/media/torrent/torrent_files/
  DIR_MEDIA_SHOW: /home/media/

  PING: /ping
  PONG: pong
services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment: *common-variables
    ports:
      - 5672:5672
      - 15672:15672
  bot:
    image: halushko/cinema-bot:0.1-pi
    environment: *common-variables
    restart: always
    container_name: "bot"
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256Mb
  text_handler:
    image: halushko/cinema-text:0.1-pi
    environment: *common-variables
    restart: always
    container_name: "text_handler"
    depends_on:
      - rabbitmq
  file_handler:
    image: halushko/cinema-file:0.1-pi
    environment: *common-variables
    restart: always
    container_name: "file_handler"
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/torrent/torrent_files:/home/torrent_files/
  torrent:
    image: halushko/cinema-torrent:0.1-pi
    environment: *common-variables
    restart: always
    container_name: "torrent"
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/:/home/media/
      - ./workdir/torrentdata/torrents:/var/lib/transmission/config/torrents
      - ./workdir/torrentdata/resume:/var/lib/transmission/config/resume
    ports:
      - 9091:9091
      - 51413:51413
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  minidlna:
    container_name: "minidlna"
    image: halushko/cinema-media:0.1-pi
    restart: always
    environment:  *common-variables
    depends_on:
      - rabbitmq
    volumes:
      - ./workdir/mediadata/torrent/complete:/home/media/
    network_mode: host
    ports:
      - 8200:8200
      - 1900:1900/udp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
