name: Build Docker Images for all projects

on:
  push:
    branches: [ test_wf ]
  pull_request:
    branches: [ test_wf ]

jobs:
  build:
  - runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2.1.0
    - uses: docker/setup-buildx-action@v2.5.0
    - run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/setup-java@v3.10.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: gradle/gradle-build-action@v2.4.0
      with:
        build-root-directory: middleware
        gradle-version: current
        arguments: jar
    - uses: docker/build-push-action@v2.6.0
      with:
        context: middleware/build/libs
        file: ./config/dockerfiles/Dockerfile-middleware
        push: true
        builder: mybuilder
        platforms: linux/amd64, linux/arm64/v8
        tags: halushko/cinema-middleware:1.0,halushko/cinema-middleware:latest

#    - name: show me
#    - run: |
#          ls middleware/build/libs; my_dir=`pwd`; echo $my_dir>my_pass.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my_pass.txt
    - run: ls middleware/build/libs; my_dir=`pwd`; echo $my_dir>my_pass.txt

    - uses: actions/download-artifact@v2
      with:
        name: my_pass.txt
    - run: $my_dir=`cat my_pass.txt`
    - uses: gradle/gradle-build-action@v2.4.0
      with:
        build-root-directory: bot
        gradle-version: current
        arguments: jar

    - uses: docker/build-push-action@v2.6.0
      with:
        context: bot/build/libs
        file: ./config/dockerfiles/Dockerfile-bot
        push: true
        builder: mybuilder
        platforms: linux/amd64, linux/arm64/v8
        tags: halushko/cinema-bot:1.0,halushko/cinema-bot:latest