name: Build Docker Images for all projects

on:
  push:
    branches: [ test_wf ]
  pull_request:
    branches: [ test_wf ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare location environments
        run: |
          echo "CONFIG_DIR=`pwd`/config" >> $GITHUB_ENV
      - name: asd
        run: |
          mkdir -p transmission/config
          cp $CONFIG_DIR/config_files/transmission/ transmission/config
          cp $CONFIG_DIR/commands/transmission/ transmission/config
        with:
          context: torrent/build/libs
        
        

#      # Preparation
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2.1.0
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2.5.0
#      - name: Create buildx builder
#        run: |
#          docker buildx create --name mybuilder --use
#          docker buildx inspect --bootstrap
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Set up Java 8
#        uses: actions/setup-java@v3.10.0
#        with:
#          distribution: 'temurin'
#          java-version: '8'
#      - name: Prepare location environments
#        run: |
#          echo "CORE_LOCATION=`pwd`/core/build/libs" >> $GITHUB_ENV
#          echo "CONFIG_DIR=`pwd`/config" >> $GITHUB_ENV
#
#      # Build Core
#      - name: Build Core
#        uses: gradle/gradle-build-action@v2.4.0
#        with:
#          build-root-directory: core
#          gradle-version: current
#          arguments: jar
#
#      # Build JARs
#      - name: Build Bot
#        uses: gradle/gradle-build-action@v2.4.0
#        with:
#          build-root-directory: bot
#          gradle-version: current
#          arguments: jar
#      - name: Build File consumer
#        uses: gradle/gradle-build-action@v2.4.0
#        with:
#          build-root-directory: fileConsumer
#          gradle-version: current
#          arguments: jar
#      - name: Copy configs
#        run: |
#          mkdir -p transmission/config
#          cp $CONFIG_DIR/config_files/transmission/ transmission/config
#          cp $CONFIG_DIR/commands/transmission/ transmission/config
#      - name: Build Text consumer
#        uses: gradle/gradle-build-action@v2.4.0
#        with:
#          build-root-directory: textConsumer
#          gradle-version: current
#          arguments: jar
#      - name: Build Torrent client
#        uses: gradle/gradle-build-action@v2.4.0
#        with:
#          build-root-directory: torrent
#          gradle-version: current
#          arguments: jar
#
#      # Push images
#      - name: Create Bot image
#        uses: docker/build-push-action@v2.6.0
#        with:
#          context: bot/build/libs
#          file: ./config/dockerfiles/Dockerfile-bot
#          push: true
#          builder: mybuilder
#          platforms: linux/amd64, linux/arm64/v8
#          tags: halushko/cinema-bot:1.0,halushko/cinema-bot:latest
#      - name: Create File consumer Image
#        uses: docker/build-push-action@v2.6.0
#        with:
#          context: fileConsumer/build/libs
#          file: ./config/dockerfiles/Dockerfile-file
#          push: true
#          builder: mybuilder
#          platforms: linux/amd64, linux/arm64/v8
#          tags: halushko/cinema-file:1.0,halushko/cinema-file:latest
#      - name: Create Text consumer Image
#        uses: docker/build-push-action@v2.6.0
#        with:
#          context: textConsumer/build/libs
#          file: ./config/dockerfiles/Dockerfile-text
#          push: true
#          builder: mybuilder
#          platforms: linux/amd64, linux/arm64/v8
#          tags: halushko/cinema-text:1.0,halushko/cinema-text:latest
#      - name: Create Torrent client Image
#        uses: docker/build-push-action@v2.6.0
#        with:
#          context: torrent/build/libs
#          file: ./config/dockerfiles/Dockerfile-torrent
#          push: true
#          builder: mybuilder
#          platforms: linux/amd64, linux/arm64/v8
#          tags: halushko/cinema-torrent:1.0,halushko/cinema-torrent:latest
#          build-args: |
#            CONFIG_DIR=$CONFIG_DIR