name: Build Docker Images for all projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [middleware]
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.project }}
        file: ../config/dockerfiles/Dockerfile-${{ matrix.project }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/cinema-${{ matrix.project }}:test-wf,${{ secrets.DOCKER_USERNAME }}/cinema-${{ matrix.project }}:test-wf-tst
