name: Build Docker Images for all projects

on:
  push:
    branches: [ test_wf ]
  pull_request:
    branches: [ test_wf ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [middleware]
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2.6.0
      with:
        context: ./middleware
        file: ./config/dockerfiles/Dockerfile-${{ matrix.project }}
        push: true
        builder: mybuilder
        platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
        tags: halushko/cinema-${{ matrix.project }}:test-wf,halushko/cinema-${{ matrix.project }}:test-wf-tst
