name: Push in beta

on:
  push:
    branches:
      - 'beta-*'
      - 'BETA-*'
    if: >
      github.ref_type == 'branch' &&
      github.base_ref == 'refs/heads/alpha/' &&
      github.ref != 'refs/heads/alpha' &&
      startsWith(github.ref, 'refs/heads/alpha/')

jobs:
  build_core:
    uses: ./.github/workflows/java-build-core.yml
    with:
      java-version: '20'
  build_jars:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/java-build-jars.yml
    with:
      repository-name: ${{ matrix.service }}
      java-version: '20'
    needs: build_core
  get_beta_tags:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/docker-get-beta-tags.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: build_jars
  push_images:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/docker-push-images.yml
    with:
      repository-name: ${{ matrix.service }}
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
    needs: get_beta_tags