name: Pull in alpha

on:
  pull_request:
    branches: [ alpha ]
  push:
    branches: [ alpha ]

jobs:
  build_core:
    uses: ./.github/workflows/build_core.yml
    with:
      java-version: '8'
  build_jars:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/build_jars.yml
    with:
      java-version: '8'
      repository-name: ${{ matrix.service }}
    needs: build_core
  get_alpha_tags:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/get_alpha_tags.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: build_jars
  push_images:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/push_images.yml
    with:
      repository-name: ${{ matrix.service }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
    needs: get_alpha_tags
  get_docker_token:
    uses: ./.github/workflows/get_docker_token.yml
    needs: push_images
  clean_beta_images:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    uses: ./.github/workflows/clean_beta_images.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: get_docker_token