name: Pull in alpha

on:
  pull_request:
    branches: [ alpha ]
  push:
    branches: [ alpha ]

env:
  SERVICE_MATRIX: '[bot,text,file,torrent]'

jobs:
  build_core:
    uses: ./.github/workflows/build_core.yml
    with:
      java-version: '8'
  build_jars:
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/build_jars.yml
    with:
      java-version: '8'
      repository-name: ${{ matrix.service }}
    needs: build_core
  get_alpha_tags:
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/jobs/getters/alpha_tags.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: build_jars
  push_images:
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/jobs/push_images.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: get_alpha_tags
  get_docker_token:
    uses: ./.github/workflows/jobs/getters/docker_token.yaml
    needs: push_images
  clean_beta_images:
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/jobs/clean_beta_images.yaml
    with:
      repository-name: ${{ matrix.service }}
    needs: get_docker_token