name: Pull in alpha

on:
  pull_request:
    branches: [ alpha ]
  push:
    branches: [ alpha ]
jobs:
  login_to_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Login to DockerHub
      run: |
        DH_RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"username":"${{ secrets.DOCKER_USERNAME }}", "password":"${{ secrets.DOCKER_PASSWORD }}"}' https://hub.docker.com/v2/users/login/)
        echo "Responce $DH_RESPONSE"
        DH_TOKEN=$(echo $DH_RESPONSE | grep -o '"token":"[^"]*' | cut -d'"' -f4)
        echo "Token $DH_TOKEN"
        echo $DH_TOKEN > token.tmp
        cat token.tmp
      shell: bash
    - name: Upload token artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dh_token_file
        path: token.tmp
  delete_beta_images:
    strategy:
      matrix:
        service: [ bot, text, file, torrent ]
    runs-on: ubuntu-latest
    needs: login_to_docker
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Download token artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: dh_token_file
          path: .
      - name: Delete beta tags
        run: |
          cat token.tmp
          ALL_TAGS=$(curl -s https://registry.hub.docker.com/v2/repositories/halushko/cinema-${{ matrix.service }}/tags?page_size=1024 | jq '.results[].name')
          echo "All tags=[$ALL_TAGS]"
          BETA_TAGS=$(echo $ALL_TAGS | grep -E "^\".+_[0-9]+\"$")
          echo "All tags=[$BETA_TAGS]"
        shell: bash