name: Pull in alpha

on:
  pull_request:
    branches: [ alpha ]
  push:
    branches: [ alpha ]

env:
  SERVICE_MATRIX: '[bot,text,file,torrent]'
  JAVA_V: '8'

jobs:
  build_core:
    env:
      JAVA_V: ${{ env.JAVA_V }}
    uses: ./.github/workflows/build_core.yml
    with:
      java-version: ${{ env.JAVA_V }}
  build_jars:
    env:
      JAVA_V: ${{ env.JAVA_V }}
      SERVICE_MATRIX: ${{ env.SERVICE_MATRIX }}
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/build_jars.yml
    with:
      java-version: ${{ env.JAVA_V }}
      repository-name: ${{ matrix.service }}
    needs: build_core
  get_alpha_tags:
    env:
      SERVICE_MATRIX: ${{ env.SERVICE_MATRIX }}
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/get_alpha_tags.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: build_jars
  push_images:
    env:
      SERVICE_MATRIX: ${{ env.SERVICE_MATRIX }}
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/push_images.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: get_alpha_tags
  get_docker_token:
    uses: ./.github/workflows/get_docker_token.yml
    needs: push_images
  clean_beta_images:
    env:
      SERVICE_MATRIX: ${{ env.SERVICE_MATRIX }}
    strategy:
      matrix:
        service: ${{ env.SERVICE_MATRIX }}
    uses: ./.github/workflows/clean_beta_images.yml
    with:
      repository-name: ${{ matrix.service }}
    needs: get_docker_token